/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/vehicles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get all vehicles
         * @description #### Controller:
         *
         *     `github.com/devmcclu/the-block/backend/domains/vehicles.VehiclesResources.getAllVehicles`
         *
         *     #### Middlewares:
         *
         *     - `github.com/go-fuego/fuego.defaultLogger.middleware`
         *
         *     ---
         */
        get: operations["GET_/vehicles/"];
        put?: never;
        /**
         * post vehicle
         * @description #### Controller:
         *
         *     `github.com/devmcclu/the-block/backend/domains/vehicles.VehiclesResources.postVehicle`
         *
         *     #### Middlewares:
         *
         *     - `github.com/go-fuego/fuego.defaultLogger.middleware`
         *
         *     ---
         */
        post: operations["POST_/vehicles/"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get config
         * @description #### Controller:
         *
         *     `github.com/devmcclu/the-block/backend/domains/vehicles.VehiclesResources.getConfig`
         *
         *     #### Middlewares:
         *
         *     - `github.com/go-fuego/fuego.defaultLogger.middleware`
         *
         *     ---
         */
        get: operations["GET_/vehicles/config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get filter options
         * @description #### Controller:
         *
         *     `github.com/devmcclu/the-block/backend/domains/vehicles.VehiclesResources.getFilterOptions`
         *
         *     #### Middlewares:
         *
         *     - `github.com/go-fuego/fuego.defaultLogger.middleware`
         *
         *     ---
         */
        get: operations["GET_/vehicles/filters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get vehicle
         * @description #### Controller:
         *
         *     `github.com/devmcclu/the-block/backend/domains/vehicles.VehiclesResources.getVehicle`
         *
         *     #### Middlewares:
         *
         *     - `github.com/go-fuego/fuego.defaultLogger.middleware`
         *
         *     ---
         */
        get: operations["GET_/vehicles/:id"];
        /**
         * put vehicle
         * @description #### Controller:
         *
         *     `github.com/devmcclu/the-block/backend/domains/vehicles.VehiclesResources.putVehicle`
         *
         *     #### Middlewares:
         *
         *     - `github.com/go-fuego/fuego.defaultLogger.middleware`
         *
         *     ---
         */
        put: operations["PUT_/vehicles/:id"];
        post?: never;
        /**
         * delete vehicle
         * @description #### Controller:
         *
         *     `github.com/devmcclu/the-block/backend/domains/vehicles.VehiclesResources.deleteVehicle`
         *
         *     #### Middlewares:
         *
         *     - `github.com/go-fuego/fuego.defaultLogger.middleware`
         *
         *     ---
         */
        delete: operations["DELETE_/vehicles/:id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description AuctionConfig schema */
        AuctionConfig: {
            max_auction_duration_hours?: number;
        };
        /** @description HTTPError schema */
        HTTPError: {
            /** @description Human readable error message */
            detail?: string | null;
            errors?: ({
                /** @description Additional information about the error */
                more?: {
                    [key: string]: unknown;
                } | null;
                /** @description For example, name of the parameter that caused the error */
                name?: string;
                /** @description Human readable error message */
                reason?: string;
            } | null)[] | null;
            instance?: string | null;
            /**
             * @description HTTP status code
             * @example 403
             */
            status?: number | null;
            /** @description Short title of the error */
            title?: string | null;
            /** @description URL of the error type. Can be used to lookup the error in a documentation */
            type?: string | null;
        };
        /** @description Vehicle schema */
        Vehicle: {
            auction_start?: string;
            bid_count?: number;
            body_style?: string;
            buy_now_price?: number | null;
            city?: string;
            /** Format: double */
            condition_grade?: number;
            condition_report?: string;
            current_bid?: number;
            damage_notes?: {
                note?: string;
                vehicle_id?: number;
            }[];
            drivetrain?: string;
            engine?: string;
            exterior_color?: string;
            external_id?: string;
            fuel_type?: string;
            images?: {
                url?: string;
                vehicle_id?: number;
            }[];
            interior_color?: string;
            lot?: string;
            make?: string;
            model?: string;
            odometer_km?: number;
            province?: string;
            reserve_price?: number | null;
            selling_dealership?: string;
            starting_bid?: number;
            title_status?: string;
            transmission?: string;
            trim?: string;
            vin?: string;
            year?: number;
        };
        /** @description VehicleCreate schema */
        VehicleCreate: {
            auction_start?: string;
            body_style?: string;
            buy_now_price?: number | null;
            city?: string;
            /** Format: double */
            condition_grade?: number;
            condition_report?: string;
            damage_notes?: string[];
            drivetrain?: string;
            engine?: string;
            exterior_color?: string;
            fuel_type?: string;
            images?: string[];
            interior_color?: string;
            lot?: string;
            make?: string;
            model?: string;
            odometer_km?: number;
            province?: string;
            reserve_price?: number | null;
            selling_dealership?: string;
            starting_bid?: number;
            title_status?: string;
            transmission?: string;
            trim?: string;
            vin?: string;
            year?: number;
        };
        /** @description VehicleFilterOptions schema */
        VehicleFilterOptions: {
            body_styles?: string[];
            /** Format: double */
            condition_max?: number;
            /** Format: double */
            condition_min?: number;
            drivetrains?: string[];
            exterior_colors?: string[];
            fuel_types?: string[];
            interior_colors?: string[];
            makes?: string[];
            models?: string[];
            odometer_max?: number;
            odometer_min?: number;
            title_statuses?: string[];
            transmissions?: string[];
            year_max?: number;
            year_min?: number;
        };
        /** @description VehicleUpdate schema */
        VehicleUpdate: {
            bid_count?: number | null;
            current_bid?: number | null;
        };
        /** @description unknown-interface schema */
        "unknown-interface": unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "GET_/vehicles/": {
        parameters: {
            query?: {
                /** @description Minimum year */
                year_min?: number;
                /** @description Maximum year */
                year_max?: number;
                /** @description Filter by make */
                make?: string[];
                /** @description Filter by model */
                model?: string[];
                /** @description Filter by body style */
                body_style?: string[];
                /** @description Filter by exterior color */
                exterior_color?: string[];
                /** @description Filter by interior color */
                interior_color?: string[];
                /** @description Filter by transmission */
                transmission?: string[];
                /** @description Filter by drivetrain */
                drivetrain?: string[];
                /** @description Filter by fuel type */
                fuel_type?: string[];
                /** @description Filter by title status */
                title_status?: string[];
                /** @description Minimum odometer (km) */
                odometer_min?: number;
                /** @description Maximum odometer (km) */
                odometer_max?: number;
                /** @description Minimum condition grade */
                condition_min?: string;
                /** @description Maximum condition grade */
                condition_max?: string;
                /** @description Sort order: price_asc, price_desc, year_desc, year_asc */
                sort?: string;
            };
            header?: {
                Accept?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                    "application/xml": components["schemas"]["Vehicle"][];
                };
            };
            /** @description Bad Request _(validation or deserialization error)_ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            /** @description Internal Server Error _(panics)_ */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "POST_/vehicles/": {
        parameters: {
            query?: never;
            header?: {
                Accept?: string;
            };
            path?: never;
            cookie?: never;
        };
        /** @description Request body for database.VehicleCreate */
        requestBody: {
            content: {
                "*/*": components["schemas"]["VehicleCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                    "application/xml": components["schemas"]["Vehicle"];
                };
            };
            /** @description Bad Request _(validation or deserialization error)_ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            /** @description Internal Server Error _(panics)_ */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GET_/vehicles/config": {
        parameters: {
            query?: never;
            header?: {
                Accept?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionConfig"];
                    "application/xml": components["schemas"]["AuctionConfig"];
                };
            };
            /** @description Bad Request _(validation or deserialization error)_ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            /** @description Internal Server Error _(panics)_ */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GET_/vehicles/filters": {
        parameters: {
            query?: never;
            header?: {
                Accept?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleFilterOptions"];
                    "application/xml": components["schemas"]["VehicleFilterOptions"];
                };
            };
            /** @description Bad Request _(validation or deserialization error)_ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            /** @description Internal Server Error _(panics)_ */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GET_/vehicles/:id": {
        parameters: {
            query?: never;
            header?: {
                Accept?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                    "application/xml": components["schemas"]["Vehicle"];
                };
            };
            /** @description Bad Request _(validation or deserialization error)_ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            /** @description Internal Server Error _(panics)_ */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "PUT_/vehicles/:id": {
        parameters: {
            query?: never;
            header?: {
                Accept?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Request body for database.VehicleUpdate */
        requestBody: {
            content: {
                "*/*": components["schemas"]["VehicleUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                    "application/xml": components["schemas"]["Vehicle"];
                };
            };
            /** @description Bad Request _(validation or deserialization error)_ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            /** @description Internal Server Error _(panics)_ */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "DELETE_/vehicles/:id": {
        parameters: {
            query?: never;
            header?: {
                Accept?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["unknown-interface"];
                    "application/xml": components["schemas"]["unknown-interface"];
                };
            };
            /** @description Bad Request _(validation or deserialization error)_ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            /** @description Internal Server Error _(panics)_ */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                    "application/xml": components["schemas"]["HTTPError"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
